### PR TITLE
chore: upgrade google-auth-library and grpc -> @grpc/grpc-js

### LINKED ISSUE #180: Use @grpc/grpc-js instead of grpc
*Is your feature request related to a problem? Please describe.*
Currently libraries use [grpc package](https://www.npmjs.com/package/grpc). Installing grpc library requires C/C++ compiler and gives errors when native C/C++ is changed/updated.

*Describe the solution you'd like*
Switch to [@grpc/grpc-js package](https://www.npmjs.com/package/@grpc/grpc-js) that is mostly compatible with grpc package while does not require any C/C++ compiler for package install.

*Describe alternatives you've considered*
Sorry, none.

*Additional context*
A handy migration guide available here https://www.npmjs.com/package/@grpc/grpc-js#migrating-from-grpc

### LINKED ISSUE #186: Update google-auth-library to ^6.1.1
There's a security vulnerability (CVSS 3 Score: 7.3 | CVSS 2 Score: 7.5) in the [node-forge](https://www.npmjs.com/package/node-forge) npm package, which is a transitive dependency from google-auth-library:

├─┬ @google-cloud/opentelemetry-cloud-trace-exporter
│ └─┬ google-auth-library
│   └─┬ gtoken
│     └─┬ google-p12-pem
│       └── node-forge

node-forge@0.10.0 has a patch for this vulnerability and [google-auth-library@6.1.1](https://github.com/googleapis/google-auth-library-nodejs/blob/master/CHANGELOG.md) has the patch in it.

### PR DESCRIPTION
**Pull request by aabmass**
Fixes #186, fixes #180 

- swap `grpc` with `@grpc/grpc-js`. `grpc` is [being deprecated](https://github.com/grpc/grpc-node/tree/grpc@1.24.x/packages/grpc-native-core) in favor of the `@grpc/grpc-js` JS implementation.
- upgrade `google-auth-library` which solves security issue in the transitive dependency `node-forge`.

### CODE REVIEW

**Review by nilebox — APPROVED** [review]

**Comment by HW13** [comment]
Hey @nilebox, will these changes be published soon? Dependabot is currently harassing my team and I with high-severity alerts 😬 . We'd really appreciate an expedited release 🙏

**Comment by nilebox** [comment]
@aabmass could you cut a new release as requested above?

**Comment by aabmass** [comment]
@HW13 just published v0.7.0

**Comment by HW13** [comment]
Awesome, thanks! 🚀

**Pull request merged**
