### PR TITLE
chore: add initial package skeleton for cloud-trace-propagator 

### PR DESCRIPTION
**Pull request by shivkanya9146**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue/feature](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here>

### CODE REVIEW

**Comment by kintel** [comment]
Does it make sense for this to be a separate package? This is only really useful when using Google Cloud Trace, so it feels like incorporating it into the Cloud Trace exporter would make sense.

Along these lines: We should probably align this across languages. To my knowledge, Javascript is the first, but the Python one is in the works.

Caveat: I don't know anything about our packaging strategy

**Comment by mayurkale22** [comment]
> This is only really useful when using Google Cloud Trace ...

I certainly agree with it. But you can use other OpenTelemetry propagators (such as `B3Format`, `HttpTraceContext`) and export to Google Cloud Trace backend. 

I reckon having an individual module / package would give great set of flexible to the end users. One known example is `cloud-trace-nodejs` library, which [depends on](https://github.com/googleapis/cloud-trace-nodejs/blob/master/package.json#L96) similar sort of a propagator. Moreover, our exporter package would be lightweight w/o propagator. I don't know if that matters. Having said that, I don't mind either way. @kintel WDYT?

**Comment by kintel** [comment]
@mayurkale22 OK, after having looked through those other packages, it makes sense to make this a separate package.
I would suggest changing the package name to `@google-cloud/opentelemetry-cloud-trace-propagator`, as "Cloud Trace" is the product name we're supporting.

**Comment by shivkanya9146** [comment]
> @mayurkale22 OK, after having looked through those other packages, it makes sense to make this a separate package.
> I would suggest changing the package name to `@google-cloud/opentelemetry-cloud-trace-propagator`, as "Cloud Trace" is the product name we're supporting.

Done:)

**Pull request merged**
