### PR TITLE
chore: upgrade peer/dev deps to @opentelemetry 0.14.0

### LINKED ISSUE #215: Cannot read property 'FAILED_RETRYABLE' of undefined
getting 
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'FAILED_RETRYABLE' of undefined` on the console

### What version of OpenTelemetry are you using?
0.13.0

### What version of Node are you using?
v14.15.1

### What did you do?
follow up instructions on https://github.com/GoogleCloudPlatform/opentelemetry-operations-js#readme to create tracing.js file
run the project by this command: `node -r ./tracing.js index.js`
sending some curl requests to the server:
`curl --location --request GET 'http://localhost:3000'`

### What did you expect to see?
I expected to not have any warning messages

### What did you see instead?
```
(node:13140) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'FAILED_RETRYABLE' of undefined
    at TraceExporter._batchWriteSpans (/home/mehran/projects/some-sample-project/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:91:40)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TraceExporter.export (/home/mehran/projects/some-sample-project/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:61:24)
(node:13140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

### Sample Project
[some-sample-project.zip](https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/files/5701372/some-sample-project.zip)
steps:
- npm install
- change values in tracing.js for your own(`projectId`, `keyFile`, `keyFileName`)
- run `node -r ./tracing.js index.js`
- run `curl --location --request GET 'http://localhost:3000'`
- you should see the warning logs after a few seconds

### PR DESCRIPTION
**Pull request by aabmass**
Fixes #215 

Upgrading peer/dev deps and fixing the associated breaking changes from upstream. Mainly:
- Propagator getters and setters were changed into classes and renamed
- `ExportResult` was changed into an object with separate `code` and `error` fields
- `ExportResult` enum is now `ExportResultCode` and `FAILED_RETRYABLE` was removed.
  * retries were never actually implemented, so this is not a functionality change
  * they decided retries should be implemented by the exporters directly, which makes sense. Tracked in #181 
- `Meter.getBatcher()` -> `Meter.getProcessor()`
- `CanonicalCode` -> `StatusCode`
- Propagators have a new `fields()` method ([see spec](https://github.com/open-telemetry/opentelemetry-specification/blob/181a1afdb201f1334fb032960bb1672cf5a0272f/specification/context/api-propagators.md#fields)).

Tested the new packages manually as well, everything is working great.

### CODE REVIEW

**Comment by electricmonk** [comment]
not sure if anyone's aware of it, but using the current stable version (0.7.0) with opentelemetry 0.13.0 causes a torrent of errors like this:
```
TypeError: Cannot read property 'FAILED_RETRYABLE' of undefined
at TraceExporter._batchWriteSpans (/app/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:91:40)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async TraceExporter.export (/app/node_modules/@google-cloud/opentelemetry-cloud-trace-exporter/build/src/trace.js:61:24)
```

**Comment by aabmass** [comment]
@electricmonk yes, this PR is the fix. The `peerDependencies` in each package are correct and things should be working as long as they are satisfied: https://github.com/GoogleCloudPlatform/opentelemetry-operations-js/blob/facb8e0b0676793593d1b4bcd7a03735650b636d/packages/opentelemetry-cloud-trace-exporter/package.json#L65-L68

**Comment by erlichmen** [comment]
ETA for release? current latest is not working (as you are all aware)

**Comment by sk-** [comment]
@aabmass note that open telemetry 0.14 was recently released.

**Review by mayurkale22 — APPROVED** [review]

**Comment by aabmass** [comment]
Thanks for review @mayurkale22 🙂

**Pull request merged**
